# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2f08d007edf0f59ca35793e893427725da52d2c944ef1274d39801a726d5bfbb1fb17ab43e7a050d37d44965e9b3b08d63fe41f1c1cbd8bb3b289c0e52c72dc9

test:
  secret_key_base: 47595835292557b4a160676c1a51125e501694eda6bb2d2169fdaf8354d0cc8117b1796349ccceb53a66893f7968a3827fb2791168d45e727ae3ce8e951f987e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
